### ISSUE TITLE
`nuxt build` fails with `Must use import to load ES Module`

### ISSUE THREAD

**Issue by odanado** [chakra-ui/chakra-ui-vue#367]
**Describe the bug**
Running `yarn nuxt build` on a project created with `create-nuxt-app` fails with an error.

**To Reproduce**
1. git clone https://github.com/odan-sandbox/nuxt-chakra-ui-es-module-error
2. yarn
3. yarn build
4. See error: https://github.com/odan-sandbox/nuxt-chakra-ui-es-module-error/runs/1618656833

```
[fatal] Must use import to load ES Module: /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/merge.js
require() of ES modules is not supported.
require() of /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/merge.js from /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/@chakra-ui/vue/src/utils/icons.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename merge.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/package.json.

  Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: node_modules/lodash-es/merge.js
  require() of ES modules is not supported.
  require() of node_modules/lodash-es/merge.js from /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/@chakra-ui/vue/src/utils/icons.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
  Instead rename merge.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from node_modules/lodash-es/package.json.
  
  at Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
  at Object.require.extensions.<computed> (node_modules/ts-node/src/index.ts:1045:43)

   ╭────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╮
   │                                                                                                                                    │
   │   ✖ Nuxt Fatal Error                                                                                                               │
   │                                                                                                                                    │
   │   Error [ERR_REQUIRE_ESM]: Must use import to load ES Module:                                                                      │
   │   /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/merge.js                  │
   │   require() of ES modules is not supported.                                                                                        │
   │   require() of                                                                                                                     │
   │   /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/merge.js                  │
   │   from                                                                                                                             │
   │   /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/@chakra-ui/vue/src/utils/icons.js   │
   │   is an ES module file as it is a .js file whose nearest parent package.json                                                       │
   │   contains "type": "module" which defines all .js files in that package scope as                                                   │
   │   ES modules.                                                                                                                      │
   │   Instead rename merge.js to end in .cjs, change the requiring code to use                                                         │
   │   import(), or remove "type": "module" from                                                                                        │
   │   /home/runner/work/nuxt-chakra-ui-es-module-error/nuxt-chakra-ui-es-module-error/node_modules/lodash-es/package.json.             │
   │                                                                                                                                    │
   │                                                                                                                                    │
   ╰────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
```

**Expected behavior**
The build will succeed.

**Additional context**
- Node.js: 14.x/12.x
- nuxt@2.14.12
- @nuxtjs/emotion@0.0.1
- @chakra-ui/nuxt@0.1.0

**Comment by odanado** [comment]
Sorry.

I upgrade to @chakra-ui/nuxt@0.2.2, @nuxtjs/emotion@0.1.0 and this error has been resolved.

**Comment by codebender828** [comment]
Hey @odanado !

Sorry about the issue. The reason is because `create-nuxt-app` takes a while to update the versions even after publishing. Will be leaving this open until it's updated.

**Comment by codebender828** [comment]
Closing this for now. Please re-open if there's an issue with this 👍
