### ISSUE TITLE
`r.keyframes is not a function` error when trying to build or run `dev` on a Nuxt site

### ISSUE THREAD

**Issue by philwolstenholme** [chakra-ui/chakra-ui-vue#391]
`npm run dev` gives me this error on a Nuxt site:

```
FATAL  r.keyframes is not a function                                                                                                                                             19:26:25

  at node_modules/@chakra-ui/vue/dist/cjs/CSpinner.js:1:396
  at p (node_modules/jiti/dist/jiti.js:1:9442)
  at node_modules/@chakra-ui/vue/dist/cjs/index.js:1:1374
  at p (node_modules/jiti/dist/jiti.js:1:9442)
  at node_modules/@chakra-ui/nuxt/lib/module.js:3:80
  at Resolver.p [as _require] (node_modules/jiti/dist/jiti.js:1:9442)
  at Resolver.requireModule (node_modules/@nuxt/core/dist/core.js:381:29)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:182:38)
  at node_modules/@nuxt/utils/dist/utils.js:638:43
  at ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)
```

I'm using these versions:

```
"@chakra-ui/nuxt": "^0.2.4",
"@nuxtjs/emotion": "^0.1.0",
"nuxt": "^2.15.2",
```

I have the same issue on Node `v10.23.0` and Node `v14.15.4`.

`keyframes` is an Emotion, function, I think? I'm not sure why the `dist` version is being used though?

Here is the Nuxt config and `package.json` files from my project

<details>
<summary>nuxt.config.js (excuse the messiness of the commented out bits, that's been part of me trying to debug)</summary>

```
import webpack from 'webpack';

export default {
  server: {
    port: 3000,
    host: '0.0.0.0',
  },
  head: {
    title: process.env.npm_package_name || '',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      {
        hid: 'description',
        name: 'description',
        content: process.env.npm_package_description || '',
      },
      { name: 'format-detection', content: 'telephone=no' },
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' },
      {
        rel: 'preconnect',
        href: 'https://fonts.gstatic.com',
        crossorigin: 'crossorigin',
      },
      {
        rel: 'preload',
        href:
          'https://fonts.googleapis.com/css?family=Raleway:300,400,400i,500,600,700|Roboto:300,300i,400,400i,500,700&display=swap',
        as: 'style',
      },
      {
        rel: 'stylesheet',
        href:
          'https://fonts.googleapis.com/css?family=Raleway:300,400,400i,500,600,700|Roboto:300,300i,400,400i,500,700&display=swap',
        media: 'print',
        onload: "this.media='all'",
      },
    ],
    script: [],
  },
  loading: { color: '#fff' },
  router: {
    middleware: ['checkout'],
  },
  buildModules: [
    // https://go.nuxtjs.dev/eslint
    '@nuxtjs/eslint-module',
    // https://go.nuxtjs.dev/stylelint
    '@nuxtjs/stylelint-module',
    // to core
    '@nuxt/typescript-build',
    '@nuxtjs/style-resources',
    // to core soon
    '@nuxtjs/pwa',
    // [
    //   '@vue-storefront/nuxt',
    //   {
    //     coreDevelopment: true,
    //     useRawSource: {
    //       dev: ['@vue-storefront/commercetools', '@vue-storefront/core'],
    //       prod: ['@vue-storefront/commercetools', '@vue-storefront/core'],
    //     },
    //   },
    // ],
    // ['@vue-storefront/nuxt-theme'],
    // [
    //   '@vue-storefront/commercetools/nuxt',
    //   {
    //     api: {
    //       uri: 'https://api.commercetools.com/vsf-ct-dev/graphql',
    //       authHost: 'https://auth.sphere.io',
    //       projectKey: 'vsf-ct-dev',
    //       clientId: 'RT4iJGDbDzZe4b2E6RyeNe9s',
    //       clientSecret: '5eBt3yfZJWw1j7V6kXjfKXpuFP-YQXpg',
    //       scopes: [
    //         'manage_products:vsf-ct-dev',
    //         'create_anonymous_token:vsf-ct-dev',
    //         'manage_my_profile:vsf-ct-dev',
    //         'manage_customer_groups:vsf-ct-dev',
    //         'view_categories:vsf-ct-dev',
    //         'introspect_oauth_tokens:vsf-ct-dev',
    //         'manage_my_payments:vsf-ct-dev',
    //         'manage_my_orders:vsf-ct-dev',
    //         'manage_my_shopping_lists:vsf-ct-dev',
    //         'view_published_products:vsf-ct-dev',
    //       ],
    //     },
    //     i18n: {
    //       useNuxtI18nConfig: true,
    //     },
    //   },
    // ],
  ],
  modules: [
    'nuxt-i18n',
    'cookie-universal-nuxt',
    'vue-scrollto/nuxt',
    '@chakra-ui/nuxt',
    '@nuxtjs/emotion',
  ],
  i18n: {
    currency: 'USD',
    country: 'US',
    countries: [
      { name: 'US', label: 'United States' },
      { name: 'AT', label: 'Austria' },
      { name: 'DE', label: 'Germany' },
      { name: 'NL', label: 'Netherlands' },
    ],
    currencies: [
      { name: 'EUR', label: 'Euro' },
      { name: 'USD', label: 'Dollar' },
    ],
    locales: [
      {
        code: 'en',
        label: 'English',
        file: 'en.js',
        iso: 'en',
      },
      {
        code: 'de',
        label: 'German',
        file: 'de.js',
        iso: 'de',
      },
    ],
    defaultLocale: 'en',
    lazy: true,
    seo: true,
    langDir: 'lang/',
    vueI18n: {
      fallbackLocale: 'en',
      numberFormats: {
        en: {
          currency: {
            style: 'currency',
            currency: 'USD',
            currencyDisplay: 'symbol',
          },
        },
        de: {
          currency: {
            style: 'currency',
            currency: 'EUR',
            currencyDisplay: 'symbol',
          },
        },
      },
    },
    detectBrowserLanguage: {
      cookieKey: 'vsf-locale',
    },
  },
  styleResources: {
    scss: [
      require.resolve('@storefront-ui/shared/styles/_helpers.scss', {
        paths: [process.cwd()],
      }),
    ],
  },
  build: {
    hotMiddleware: {
      client: {
        overlay: false,
      },
    },
    transpile: ['vee-validate/dist/rules'],
    babel: {
      ignore: [/[/\\]core-js/, /@babel[/\\]runtime/],
    },
    plugins: [
      new webpack.DefinePlugin({
        'process.VERSION': JSON.stringify({
          // eslint-disable-next-line global-require
          version: require('./package.json').version,
          lastCommit: process.env.LAST_COMMIT || '',
        }),
      }),
    ],
  },
  components: true,
  storybook: {
    stories: ['/pages/*.stories.js', '/layouts/*.stories.js'],
  },
  chakra: {
    config: {
      autoImport: true,
    },
  },
};
```
</details>

<details>
<summary>package.json</summary>

```
{
  "name": "vervent",
  "version": "1.0.0",
  "private": true,
  "scripts": {
    "dev": "nuxt",
    "build": "nuxt build -m",
    "build:analyze": "nuxt build -a -m",
    "start": "nuxt start",
    "generate": "nuxt generate",
    "test": "jest",
    "lint:js": "eslint --ext \".js,.vue\" --fix --ignore-path .gitignore .",
    "lint:style": "stylelint \"**/*.{vue,css}\" --fix --ignore-path .gitignore",
    "lint": "npm run lint:js; npm run lint:style"
  },
  "lint-staged": {
    "*.{js,vue}": "eslint",
    "*.{css,vue}": "stylelint"
  },
  "husky": {
    "hooks": {
      "commit-msg": "commitlint -E HUSKY_GIT_PARAMS",
      "pre-commit": "lint-staged"
    }
  },
  "dependencies": {
    "@chakra-ui/nuxt": "^0.2.4",
    "@nuxtjs/emotion": "^0.1.0",
    "@nuxtjs/pwa": "^3.2.2",
    "@storefront-ui/vue": "0.9.2",
    "@vue-storefront/commercetools": "^1.1.1",
    "@vue-storefront/nuxt": "^2.2.1",
    "@vue-storefront/nuxt-theme": "^2.2.1",
    "cookie-universal-nuxt": "^2.1.3",
    "core-js": "^3.8.3",
    "nuxt": "^2.15.2",
    "nuxt-i18n": "^6.5.0",
    "vee-validate": "^3.2.3",
    "vue-scrollto": "^2.17.1"
  },
  "devDependencies": {
    "@nuxt/types": "^0.7.9",
    "@nuxtjs/eslint-config": "^5.0.0",
    "@nuxtjs/eslint-module": "^3.0.2",
    "@nuxtjs/storybook": "^3.3.1",
    "@nuxtjs/stylelint-module": "^4.0.0",
    "@vue/test-utils": "^1.0.0-beta.27",
    "babel-eslint": "^10.1.0",
    "babel-jest": "^24.1.0",
    "chakra-loader": "^1.0.3",
    "eslint": "^7.20.0",
    "eslint-config-prettier": "^8.0.0",
    "eslint-plugin-nuxt": "^2.0.0",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.6.0",
    "husky": "^5.1.1",
    "jest": "^24.1.0",
    "lint-staged": "^10.5.4",
    "prettier": "^2.2.1",
    "stylelint": "^13.11.0",
    "stylelint-config-prettier": "^8.0.2",
    "stylelint-config-recommended-scss": "^4.2.0",
    "stylelint-config-standard": "^20.0.0",
    "stylelint-scss": "^3.19.0",
    "ts-node": "^9.1.1",
    "vue-jest": "^4.0.0-0"
  }
}

```
</details>

**Comment by philwolstenholme** [comment]
I got around this by removing parts of my `nuxt.config.js` and `package.json` until it worked - I wish I knew why! I suspect some existing config from my project (Babel perhaps?) was interfering with Chakra UI.
