### ISSUE TITLE
Errors on yarn install

### ISSUE THREAD

**Issue by younho9** [chakra-ui/chakra-ui-vue#513]
**Describe the bug**

When I install dependencies using yarn, an error occurs. Then no other commands are executed.

**To Reproduce**

`yarn install` at develop or master branch.
After, `yarn docs:dev` and [Code contribution ](https://vue.chakra-ui.com/contributing#code-contribution) also not run.

**Screenshots**

```
❯ yarn          
yarn install v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "@babel/preset-env > @babel/plugin-bugfix-v8-spread-parameters-in-optional-chaining@7.14.5" has incorrect peer dependency "@babel/core@^7.13.0".
warning "@babel/preset-env > @babel/plugin-proposal-class-static-block@7.14.5" has incorrect peer dependency "@babel/core@^7.12.0".
warning "@nuxtjs/eslint-config > eslint-plugin-import@2.19.1" has incorrect peer dependency "eslint@2.x - 6.x".
warning "@nuxtjs/eslint-config > eslint-plugin-vue@6.2.2" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "@nuxtjs/eslint-config > eslint-plugin-unicorn > eslint-template-visitor@1.1.0" has incorrect peer dependency "eslint@^6.4.0".
warning "eslint-plugin-testing-library > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
warning " > @nuxtjs/eslint-module@1.1.0" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > eslint-loader@3.0.4" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning " > eslint-loader@3.0.4" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
warning "@storybook/addon-actions > @storybook/api@5.3.18" has unmet peer dependency "regenerator-runtime@*".
warning "@storybook/addon-actions > @storybook/components@5.3.18" has unmet peer dependency "react-dom@*".
warning " > @storybook/theming@5.3.18" has unmet peer dependency "react@*".
warning " > @storybook/theming@5.3.18" has unmet peer dependency "react-dom@*".
warning "@storybook/addon-actions > @storybook/api > @reach/router@1.3.3" has unmet peer dependency "react-dom@15.x || 16.x || 16.4.0-alpha.0911da3".
warning "@storybook/addon-links > @storybook/router@5.3.18" has unmet peer dependency "react@*".
warning "@storybook/addon-links > @storybook/router@5.3.18" has unmet peer dependency "react-dom@*".
warning " > @storybook/addon-centered@5.3.18" has unmet peer dependency "react-dom@*".
warning " > @storybook/addon-centered@5.3.18" has unmet peer dependency "regenerator-runtime@*".
warning " > @storybook/addon-links@5.3.18" has unmet peer dependency "react@*".
warning "@storybook/vue > @storybook/core@5.3.18" has unmet peer dependency "react@*".
warning "@storybook/vue > @storybook/core@5.3.18" has unmet peer dependency "react-dom@*".
warning " > @testing-library/user-event@10.0.1" has unmet peer dependency "@testing-library/dom@>=5".
warning " > babel-loader@8.1.0" has unmet peer dependency "webpack@>=2".
warning "@vue/eslint-config-standard > eslint-plugin-import@2.20.2" has incorrect peer dependency "eslint@2.x - 6.x".
warning " > breadstick@0.2.14" has unmet peer dependency "animejs@^3.1.0".
warning " > eslint-plugin-testing-library@3.3.1" has incorrect peer dependency "eslint@^5 || ^6".
warning " > eslint-plugin-vue@5.2.3" has incorrect peer dependency "eslint@^5.0.0".
warning "eslint-plugin-vue > vue-eslint-parser@5.0.0" has incorrect peer dependency "eslint@^5.0.0".
warning " > eslint-plugin-vue-a11y@0.0.31" has incorrect peer dependency "eslint@^3 || ^4 || ^5".
warning "eslint-plugin-vue-a11y > eslint-plugin-jsx-a11y@6.2.3" has incorrect peer dependency "eslint@^3 || ^4 || ^5 || ^6".
warning "eslint-plugin-vue-a11y > vue-eslint-parser@6.0.5" has incorrect peer dependency "eslint@^5.0.0 || ^6.0.0".
warning "nuxt > @nuxt/components@2.2.1" has unmet peer dependency "consola@*".
warning "rollup-plugin-vue > @vue/component-compiler@4.2.0" has unmet peer dependency "postcss@>=6.0".
warning " > sass-loader@8.0.2" has unmet peer dependency "webpack@^4.36.0 || ^5.0.0".
warning " > vue-loader@15.9.1" has unmet peer dependency "css-loader@*".
warning " > vue-loader@15.9.1" has unmet peer dependency "webpack@^3.0.0 || ^4.1.0 || ^5.0.0-0".
[4/4] 🔨  Building fresh packages...
[7/42] ⠁ fsevents
[8/42] ⠁ iltorb
[10/42] ⠁ electron
[9/42] ⠁ core-js
warning Error running install script for optional dependency: "/Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/@vue/cli-plugin-unit-jest/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/@vue/cli-plugin-unit-jest/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.6 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/opt/python@3.9/bin/python3 -c import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack   File \"<string>\", line 1
gyp ERR! stack     import sys; print \"%s.%s.%s\" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:441:11)
gyp ERR! stack     at Socket.emit (events.js:400:28)
gyp ERR! stack     at Pipe.<anonymous> (net.js:675:12)
gyp ERR! System Darwin 21.2.0
gyp ERR! command \"/Users/younho9/.nvm/versions/node/v14.17.6/bin/node\" \"/Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/.bin/node-gyp\" \"rebuild\"
gyp ERR! cwd /Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/@vue/cli-plugin-unit-jest/node_modules/fsevents
[7/42] ⠄ fsevents
[8/42] ⠄ iltorb
[10/42] ⠄ electron
[12/42] ⠄ nuxt
error /Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/iltorb: Command failed.
Exit code: 1
Command: node ./scripts/install.js || node-gyp rebuild
Arguments: 
Directory: /Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/iltorb
Output:
info looking for cached prebuild @ /Users/younho9/.npm/_prebuilds/82ff49-iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
http request GET https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
http 404 https://github.com/nstepien/iltorb/releases/download/v2.4.5/iltorb-v2.4.5-node-v83-darwin-x64.tar.gz
WARN install No prebuilt binaries found (target=14.17.6 runtime=node arch=x64 libc= platform=darwin)
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@14.17.6 | darwin | x64
gyp ERR! configure error 
gyp ERR! stack Error: Command failed: /usr/local/opt/python@3.9/bin/python3 -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                       ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack 
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:390:12)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at maybeClose (internal/child_process.js:1055:16)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
gyp ERR! System Darwin 21.2.0
gyp ERR! command "/Users/younho9/.nvm/versions/node/v14.17.6/bin/node" "/Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /Users/younho9/repositories/github/fork/chakra-ui-vue/node_modules/iltorb
```

**Comment by younho9** [comment]
Related: https://stackoverflow.com/questions/69936116/yarn-install-failing-import-sys-print-s-s-s-sys-version-info3-invalid

**Comment by peoray** [comment]
@younho9 what version of node are you using? Try v12

**Comment by younho9** [comment]
@peoray I used the v16. It works well in v12. Thank you.
