### ISSUE TITLE
TypeError: defu is not a function in a fresh installation

### ISSUE THREAD

**Issue by 0xcrypto** [chakra-ui/chakra-ui-vue#531]
https://github.com/chakra-ui/chakra-ui-vue/blob/f4e9f004b118c7ea3892c5669fee9e3ef6da3aaf/packages/chakra-ui-nuxt/lib/module.js#L2

defu is incorrectly imported in above mentioned line and throws error in a fresh installation.

```
vi@vi:~/source/example-app$ npm run dev

> example-app@1.0.0 dev
> nuxt


 FATAL  defu is not a function                                                                                                                                                             18:36:00

  at module.exports (node_modules/@chakra-ui/nuxt/lib/module.js:20:32)
  at ModuleContainer.addModule (node_modules/@nuxt/core/dist/core.js:239:34)
  at node_modules/@nuxt/utils/dist/utils.js:639:43
  at async ModuleContainer.ready (node_modules/@nuxt/core/dist/core.js:55:5)
  at async Nuxt._init (node_modules/@nuxt/core/dist/core.js:478:5)


   ╭───────────────────────────────────────╮
   │                                       │
   │   ✖ Nuxt Fatal Error                  │
   │                                       │
   │   TypeError: defu is not a function   │
   │                                       │
   ╰───────────────────────────────────────╯
```

It needs to be destructured:
```js
const { defu } = require('defu') // works fine
```

**Comment by 0xcrypto** [comment]
Manually installing defu@^2.0.4 works too.

**Comment by ShadeAJ1** [comment]
Just did a fresh setup with nuxt and I'm still getting this issue. Fixed it by installing manually.
